# Generated by Django 3.2.3 on 2021-05-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
