# Generated by Django 3.2.3 on 2021-05-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_review_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='comment',
            new_name='content',
        ),
    ]
