# Generated by Django 3.2.3 on 2021-05-25 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(default=uuid.uuid4, unique=True),
        ),
    ]
